### ISSUE TITLE
Nashviva on hold

### ISSUE THREAD

**Issue by beck410** [code-for-nashville/nashviva#52]
Hi all
We are going to put Nashviva on hold for the moment to focus on launching Inclucivics and come up with a project proposal for Nashviva - We're looking to revive it for Hack Tenessee and hoping to build a solid foundation for it there - let us know if this is something you would like to be involved in.

We'd like to make Nashviva an entry point for most of the GIS based app ideas pitched to Code For Nashville. We'd love for people to help in planning how this can be done and Nashviva's future.

**Comment by mshenfield** [comment]
I think we're jumping back into this. It's a small project, but once it is up and running it should be dead simple to maintain.
